FROM python:3.11-slim
# FROM python:3.10-slim
# FROM python:3.9-slim

LABEL maintainer "Kyrylo Malakhov <malakhovks@nas.gov.ua>"
LABEL description "medlocalgpt - Ask your (medical) dataset privately using LLMs and Embeddings. No data leaves your infrastructure/platform and 100% private. Optionally you can use OpenAI GPT models or other LLM SaaS solutions."

COPY . /medlocalgpt
WORKDIR /medlocalgpt

# Expose the port uWSGI will listen on
EXPOSE 5000

RUN apt-get -y clean \
    && apt-get -y update \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential \
    && apt-get -y install unzip \
    && apt-get -y install curl \
    && apt-get -y install wget \
    && curl https://getmic.ro | bash \
    # ------------------------------------------------------------------
    && pip install -r ./deploy/requirements.txt --src /usr/local/src \
    && rm -rf /root/.cache/* \
    && apt-get -y clean \
    && apt-get -y autoremove

RUN chmod +x ./start.sh
CMD ["./start.sh"]
