# FROM python:3.11-slim
FROM python:3.10-slim

LABEL maintainer "Kyrylo Malakhov <malakhovks@nas.gov.ua>"
LABEL description "medlocalgpt - Ask your (medical) dataset privately using LLMs and Embeddings. No data leaves your infrastructure/platform and 100% private. Optionally you can use OpenAI GPT models or other LLM SaaS solutions."

COPY . /medlocalgpt
WORKDIR /medlocalgpt

# Expose the port uWSGI will listen on
EXPOSE 5000

RUN apt-get -y clean \
    && apt-get -y update \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential \
    && apt-get -y install unzip \
    && apt-get -y install curl \
    && apt-get -y install wget \
    && curl https://getmic.ro | bash \
    # ------------------------------------------------------------------
    && pip install -r ./deploy/requirements.txt --src /usr/local/src \
    # && wget -O ./ebsco-rehabilitation-dataset.zip https://cdn.e-rehab.pp.ua/u/ebsco-rehabilitation-dataset.zip \
    # && unzip ./ebsco-rehabilitation-dataset.zip -d ./SOURCE_DOCUMENTS \
    # && rm -r ./ebsco-rehabilitation-dataset.zip \
    # empty directory named “.cache”
    && rm -rf /root/.cache/* \
    && apt-get -y clean \
    && apt-get -y autoremove
    # && chmod 777 /var/run/docker.sock
    # && chmod 777 /root/.cache

RUN chmod +x ./start.sh
CMD ["./start.sh"]
